### ISSUE TITLE
[FEATURE] - DYNAMIC MATRIX JOB FOR ANSIBLE COLLECTION BUILD

### ISSUE THREAD

**Issue by patrick-hermann-sva** [stuttgart-things/stuttgart-things#190]
PUSH IN BRANCH + PATH + GET CHANGED FILES AND EXPORT TO JSON + MATRIX USE DYNAMIC JSON

https://github.com/marketplace/actions/changed-files

https://josh-ops.com/posts/github-actions-dynamic-matrix/

hardcoded:
```
---
name: Build Ansible Collection
on:
  push:
    branches:
      - main
    paths:
      - 'ansible/collections/*'

jobs:
  Build-Collections:
    strategy:
      matrix:
        collection-file: [base-os, container]
    uses: stuttgart-things/stuttgart-things/.github/workflows/call-ansible-collection.yaml@main
    with:
      runs-on: ghr-stuttgart-things-labda-test
      environment-name: k8s
      continue-error: false
      collection-file: ansible/collections/${{ matrix.collection-file }}.yaml
```
