### ISSUE TITLE
[FEATURE][AWX] - ADD PLAYBOOK FOR CREATING INSTALL-DOCKER

### ISSUE THREAD

**Issue by patrick-hermann-sva** [stuttgart-things/stuttgart-things#254]
- [x] ORGA
- [x] SCM CREDS
- [x] MACHINE CREDS
- [x] INVENTORY + HOST
- [x] PROJECT
- [x] EE 
- [x] JOB TEMPLATE
- [x] SURVEY

SURVEY:
```yaml
    docker_install_compose: true
    install_kind: false
    #kind_version: 0.22.0
    #kubectl_version: 1.30.0
```

```yaml
---
- hosts: localhost
  vars:
    controller_host: "{{ lookup('env', 'CONTROLLER_HOST') }}"
    controller_username: "{{ lookup('env', 'CONTROLLER_USERNAME') }}"
    controller_password: "{{ lookup('env', 'CONTROLLER_PASSWORD') }}"

    organizations:
      stuttgartThings:
        name: stuttgart-things
        description: stuttgart-things organization
        state: present
    scmCredentials:
      sthingsSCM:
        name: sthings-scm
        organization: stuttgart-things
        state: present
        awx_ssh_key: "{{ lookup('file', '~/.ssh/id_rsa') }}"

  tasks:
    - name: Create organizations
      awx.awx.organization:
        name: "{{ item.value.name }}"
        description: "{{ item.value.description }}"
        state: "{{ item.value.state }}"
        galaxy_credentials:
          - Ansible Galaxy
        validate_certs: no
      loop: "{{ lookup('dict', organizations, wantlist=True) }}"
  
    - name: Create a valid SCM credential from a private_key file
      awx.awx.credential:
        name: "{{ item.value.name }}"
        organization: "{{ item.value.organization }}"
        state: "{{ item.value.state }}"
        credential_type: Source Control
        inputs:
          ssh_key_data: "{{ item.value.awx_ssh_key }}"
        validate_certs: no
      loop: "{{ lookup('dict', scmCredentials, wantlist=True) }}"
```

```

**Comment by andre-ebert-sva** [comment]
```
cat <<EOF > /tmp/surveys/my_survey.json
{
    "name": "",
    "description": "",
    "spec": [
      {
        "question_name": "install docker compose?",
        "question_description": "choose true or false",
        "required": true,
        "type": "multiplechoice",
        "variable": "docker_install_compose",
        "choices": ["true", "false"],
        "min": null,
        "max": null,
        "default": "true"
      },
      {
        "question_name": "install kind?",
        "question_description": "choose true or false",
        "required": true,
        "type": "multiplechoice",
        "variable": "install_kind",
        "choices": ["true", "false"],
        "min": null,
        "max": null,
        "default": "false"
      },
      {
        "question_name": "kind version?",
        "question_description": "choose kind version",
        "required": true,
        "type": "multiplechoice",
        "variable": "kind_version",
        "choices": ["0.23.0", "0.22.0", "0.21.0", "0.20.0"],
        "min": null,
        "max": null,
        "default": "0.22.0"
      },
      {
        "question_name": "kubectl version?",
        "question_description": "choose kubectl version",
        "required": true,
        "type": "multiplechoice",
        "variable": "kubectl_version",
        "choices": ["1.30.0", "1.29.0", "1.28.0", "1.27.0"],
        "min": null,
        "max": null,
        "default": "1.30.0"
      }
    ] 
  }
EOF
```

```
cat <<EOF > /tmp/awx-play.yaml
---
- hosts: localhost
  vars:
    controller_host: "{{ lookup('env', 'CONTROLLER_HOST') }}"
    controller_username: "{{ lookup('env', 'CONTROLLER_USERNAME') }}"
    controller_password: "{{ lookup('env', 'CONTROLLER_PASSWORD') }}"

    vault_approle_id: "{{ lookup('env', 'VAULT_ROLE_ID') }}"
    vault_approle_secret: "{{ lookup('env', 'VAULT_SECRET_ID') }}"
    vault_url: "{{ lookup('env', 'VAULT_ADDR') }}"

    organizations:
      stuttgartThings:
        name: code-stuttgart-things
        description: stuttgart-things organization
        state: present

    machineCredentials:
      sthingsSSH:
        name: code-sthings-ssh
        description: stuttgart-things organization
        organization: code-stuttgart-things
        state: present
        user: sthings
        password: Atlan7is
        #awx_ssh_key: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=ssh/data/sthings:privateKey validate_certs=false auth_method=approle role_id={{ vault_approle_id }} secret_id={{ vault_approle_secret }} url={{ vault_url }}') }}"

    scmCredentials:
      sthingsSCM:
        name: code-sthings-scm
        organization: code-stuttgart-things
        state: present
        awx_ssh_key: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=ssh/data/sthings:privateKey validate_certs=false auth_method=approle role_id={{ vault_approle_id }} secret_id={{ vault_approle_secret }} url={{ vault_url }}')  | b64decode }}"

    projects:
      stuttgartThings:
        name: code-stuttgart-things
        description: 
        organization: code-stuttgart-things
        scm_url: git@codehub.sva.de:Lab/stuttgart-things/stuttgart-things.git
        scm_type: git
        credential: code-sthings-scm
        state: present
        scm_update_on_launch: true
        scm_update_cache_timeout: 120

    execution_environment:
      sthings-ee:
        name: sthings-ee
        image: eu.gcr.io/stuttgart-things/sthings-awxee:23.6.0

    inventories:
      testServer:
        name: code-inv
        description: stuttgart-things organization
        organization: code-stuttgart-things
        state: present

    host_vm:
      u24:
        name: ubuntu24-awx-test.labul.sva.de
        description: stuttgart-things organization
        inventory: code-inv
        state: present

    job_templates:
      stuttgartThings:
        name: code-install-docker
        organization: code-stuttgart-things
        inventory: code-inv
        project: code-stuttgart-things
        playbook: plays/install-docker.yaml
        credentials: code-sthings-ssh
        executionenv: sthings-ee
        state: present
        survey_enabled: true
        survey_spec: "{{ lookup('file', 'surveys/my_survey.json') }}"

  tasks:
    - name: Create organizations
      awx.awx.organization:
        name: "{{ item.value.name }}"
        description: "{{ item.value.description }}"
        state: "{{ item.value.state }}"
        galaxy_credentials:
          - Ansible Galaxy
        validate_certs: false
      loop: "{{ lookup('dict', organizations, wantlist=True) }}"

    - name: Add machine credential
      awx.awx.credential:
        name: "{{ item.value.name }}"
        description: "{{ item.value.description }}"
        organization: "{{ item.value.organization }}"
        credential_type: Machine
        state: "{{ item.value.state }}"
        inputs:
          username: "{{ item.value.user }}"
          password: "{{ item.value.password }}"
          #ssh_key_data: "{{ item.value.awx_ssh_key }}"
        validate_certs: false
      loop: "{{ lookup('dict', machineCredentials, wantlist=True) }}"

    - name: Create a valid SCM credential from a private_key file
      awx.awx.credential:
        name: "{{ item.value.name }}"
        organization: "{{ item.value.organization }}"
        state: "{{ item.value.state }}"
        credential_type: Source Control
        inputs:
          ssh_key_data: "{{ item.value.awx_ssh_key }}"
        validate_certs: false
      loop: "{{ lookup('dict', scmCredentials, wantlist=True) }}"

    - name: Add inventory
      awx.awx.inventory:
        name: "{{ item.value.name }}"
        description: "{{ item.value.description | default (omit) }}"
        organization: "{{ item.value.organization }}"
        state: "{{ item.value.state }}"
        validate_certs: false
      loop: "{{ lookup('dict', inventories, wantlist=True) }}"

    - name: Add host
      awx.awx.host:
        name: "{{ item.value.name }}"
        description: "{{ item.value.description | default (omit) }}"
        inventory: "{{ item.value.inventory }}"
        state: "{{ item.value.state }}"
        variables: "{{ item.value.vmVariables | default (omit) }}"
        validate_certs: false
      loop: "{{ lookup('dict', host_vm, wantlist=True) }}"

    - name: Create projects
      awx.awx.project:
        name: "{{ item.value.name }}"
        description: "{{ item.value.description }}"
        organization: "{{ item.value.organization }}"
        scm_url: "{{ item.value.scm_url }}"
        scm_type: "{{ item.value.scm_type }}"
        credential: "{{ item.value.credential }}"
        state: "{{ item.value.state }}"
        scm_update_on_launch: "{{ item.value.scm_update_on_launch | default(omit) }}"
        scm_update_cache_timeout: "{{ item.value.scm_update_cache_timeout | default(omit) }}"
        validate_certs: false
      loop: "{{ lookup('dict', projects, wantlist=True) }}"

    - name: Add EE to the controller instance
      awx.awx.execution_environment:
        name: "{{ item.value.name }}"
        image: "{{ item.value.image }}"
        validate_certs: false
      loop: "{{ lookup('dict', execution_environment, wantlist=True) }}"

    - name: Create job templates
      awx.awx.job_template:
        name: "{{ item.value.name }}"
        job_type: "run"
        organization: "{{ item.value.organization }}"
        inventory: "{{ item.value.inventory }}"
        project: "{{ item.value.project }}"
        playbook: "{{ item.value.playbook }}"
        credentials: "{{ item.value.credentials }}"
        execution_environment: "{{ item.value.executionenv }}"
        state: "{{ item.value.state }}"
        validate_certs: true
        survey_enabled: "{{ item.value.survey_enabled | default(omit) }}"
        survey_spec: "{{ item.value.survey_spec | default(omit) }}"
        extra_vars: "{{ item.value.extraVars | default(omit) }}"
      loop: "{{ lookup('dict', job_templates, wantlist=True) }}"

EOF
```
