### ISSUE TITLE
[AWX] - CREATE DYNAMIC VCENTER INVENTORY

### ISSUE THREAD

**Issue by patrick-hermann-sva** [stuttgart-things/stuttgart-things#272]
- [x] CREATE CREDENTIALS KIND VCENTER (LABUL CREDS)
- [x] CREATE INVENTORY 
- [x] CREATE INVENTORY SOURCE VCENTER [MODULE](https://docs.ansible.com/ansible/latest/collections/awx/awx/inventory_source_module.html)

SOURCE VARIABLES:

```yaml
---
hostnames: 
- config.name
properties:
- name
- network
- overallStatus
- value
- capability
- config
- guest
- runtime
- summary
with_nested_properties: true
with_tags: true

resources:
  - datacenter:
      - LabUL
    resources:
      - folder:
        - stuttgart-things
```

- [x] TEST AND CREATE WITH A SINGLE PLAYBOOK FOR CREATING ALL RESOURCES

**Comment by andre-ebert-sva** [comment]
```
---
- hosts: localhost
  vars:
    controller_host: "{{ lookup('env', 'CONTROLLER_HOST') }}"
    controller_username: "{{ lookup('env', 'CONTROLLER_USERNAME') }}"
    controller_password: "{{ lookup('env', 'CONTROLLER_PASSWORD') }}"
    vault_approle_id: "{{ lookup('env', 'VAULT_ROLE_ID') }}"
    vault_approle_secret: "{{ lookup('env', 'VAULT_SECRET_ID') }}"
    vault_url: "{{ lookup('env', 'VAULT_ADDR') }}"

    machineCredentials:
      vcenterCredentials:
        name: sthings-labul
        description: stuttgart-things organization
        organization: stuttgart-things
        credential_type: VMware vCenter
        state: present
        inputs:
          host: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=cloud/data/vsphere:ip validate_certs=false auth_method=approle role_id={{ vault_approle_id }} secret_id={{ vault_approle_secret }} url={{ vault_url }}') }}"
          username: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=cloud/data/vsphere:username validate_certs=false auth_method=approle role_id={{ vault_approle_id }} secret_id={{ vault_approle_secret }} url={{ vault_url }}') }}"
          password: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=cloud/data/vsphere:password validate_certs=false auth_method=approle role_id={{ vault_approle_id }} secret_id={{ vault_approle_secret }} url={{ vault_url }}') }}"

    inventories:
      testServer:
        name: test-dynamic
        description: stuttgart-things organization
        organization: stuttgart-things
        state: present

    inventorySource:
      dynamicInventory:
        name: source-test-dynamic
        description: Source for inventory test-dynamic
        organization: stuttgart-things
        inventory: test-dynamic
        credential: sthings-labul
        source: vmware

  tasks:
    - name: Add machine credential
      awx.awx.credential:
        name: "{{ item.value.name }}"
        description: "{{ item.value.description }}"
        organization: "{{ item.value.organization }}"
        credential_type: "{{ item.value.credential_type }}"
        state: "{{ item.value.state }}"
        inputs:
          host: "{{ item.value.inputs.host }}"
          username: "{{ item.value.inputs.username }}"
          password: "{{ item.value.inputs.password }}"
        validate_certs: false
      loop: "{{ lookup('dict', machineCredentials, wantlist=True) }}"

    - name: Add inventory
      awx.awx.inventory:
        name: "{{ item.value.name }}"
        description: "{{ item.value.description | default (omit) }}"
        organization: "{{ item.value.organization }}"
        state: "{{ item.value.state }}"
        validate_certs: false
      loop: "{{ lookup('dict', inventories, wantlist=True) }}"

    - name: Add an inventory source
      awx.awx.inventory_source:
        name: "{{ item.value.name }}"
        description: "{{ item.value.description }}"
        inventory: "{{ item.value.inventory }}"
        credential: "{{ item.value.credential }}"
        overwrite: true
        update_on_launch: true
        source: "{{ item.value.source }}"
        organization: "{{ item.value.organization }}"
        source_vars:
          hostnames: 
            - config.name
          properties:
            - name
            - network
            - overallStatus
            - value
            - capability
            - config
            - guest
            - runtime
            - summary
          with_nested_properties: true
          with_tags: true
          resources:
            - datacenter:
                - LabUL
              resources:
                - folder:
                  - stuttgart-things
      loop: "{{ lookup('dict', inventorySource, wantlist=True) }}"

```
