### ISSUE TITLE
[AWX] - Project sync

### ISSUE THREAD

**Issue by andre-ebert-sva** [stuttgart-things/stuttgart-things#584]
- [x] add in creation_task a task to api call the project id (generic)
- [x] give sync task generic id value

**Comment by andre-ebert-sva** [comment]
workflow.yaml
```
---
- hosts: "{{ target_host | default('localhost') }}"

  vars_files:
    - "{{ path | default('.') }}/awx-local-env.yaml"
    - "{{ path | default('.') }}/organization-sthings.yaml"
    - "{{ path | default('.') }}/scm-creds-sthings.yaml"
    - "{{ path | default('.') }}/projects-sthings.yaml"
    - "{{ path | default('.') }}/machine-creds-sthings.yaml"
    - "{{ path | default('.') }}/custom-credentials.yaml"
    - "{{ path | default('.') }}/custom-credential-type.yaml"
    - "{{ path | default('.') }}/dynamic-inventory-vsphere.yaml"
    - "{{ path | default('.') }}/inventory-source.yaml"
    - "{{ path | default('.') }}/ee-sthings.yaml"
    - "{{ path | default('.') }}/job-workflow.yaml"

  tasks:
    - ansible.builtin.import_tasks: check_connection.yaml
    - ansible.builtin.import_tasks: creation_tasks.yaml
```

------------------------------------------------------
creation_task.yaml
```
---
- name: Delete default resources
  block:
    - name: Delete Demo job template
      awx.awx.job_template:
        name: "Demo Job Template"
        state: "absent"
        organization: Default
        validate_certs: false
    - name: Delete Demo credentials
      awx.awx.credential:
        name: "Demo Credential"
        state: "absent"
        credential_type: "Machine"
        validate_certs: false
    - name: Delete Demo Host
      awx.awx.host:
        name: "localhost"
        state: "absent"
        inventory: "Demo Inventory"
        validate_certs: false
    - name: Delete Demo inventory
      awx.awx.inventory:
        name: "Demo Inventory"
        state: "absent"
        organization: "Default"
        validate_certs: false
    - name: Delete Demo Project
      awx.awx.project:
        name: "Demo Project"
        state: "absent"
        organization: Default
        validate_certs: false
    - name: Delete Demo organization
      awx.awx.organization:
        name: "Default"
        state: "absent"
        validate_certs: false
  tags: [ 'init' ]
  when: "'init' in ansible_run_tags"

- name: Create organizations
  awx.awx.organization:
    name: "{{ item.value.name }}"
    description: "{{ item.value.description }}"
    state: "{{ item.value.state }}"
    galaxy_credentials:
      - Ansible Galaxy
    validate_certs: false
  loop: "{{ lookup('dict', organizations, wantlist=True) }}"
  when: organizations is defined

- name: Add machine credential
  awx.awx.credential:
    name: "{{ item.value.name }}"
    description: "{{ item.value.description }}"
    organization: "{{ item.value.organization }}"
    credential_type: "{{ item.value.credential_type }}"
    state: "{{ item.value.state }}"
    inputs:
      username: "{{ item.value.username | default (omit) }}"
      password: "{{ item.value.password | default (omit) }}"
      ssh_key_data: "{{ item.value.awx_ssh_key | default (omit) }}"
      host: "{{ item.value.host | default (omit) }}"
    validate_certs: false
  loop: "{{ lookup('dict', machineCredentials, wantlist=True) }}"
  when: machineCredentials is defined

- name: Create a valid SCM credential from a private_key file
  awx.awx.credential:
    name: "{{ item.value.name }}"
    organization: "{{ item.value.organization }}"
    state: "{{ item.value.state }}"
    credential_type: Source Control
    inputs:
      ssh_key_data: "{{ item.value.awx_ssh_key }}"
    validate_certs: false
  loop: "{{ lookup('dict', scmCredentials, wantlist=True) }}"
  when: scmCredentials is defined

- name: Create custom credential type
  awx.awx.tower_credential_type:
    name: "{{ item.value.name }}"
    kind: "{{ item.value.kind }}"
    state: "{{ item.value.state }}"
    inputs: "{{ item.value.inputs }}"
    injectors: "{{ item.value.injectors }}"
    validate_certs: false
  loop: "{{ lookup('dict', custom_credential_types, wantlist=True) }}"
  when: custom_credential_types is defined

- name: Create custom credential from custom credential type
  awx.awx.tower_credential:
    name: "{{ item.value.name }}"
    organization: "{{ item.value.organization }}"
    credential_type: "{{ item.value.credential_type }}"
    description: "{{ item.value.description }}"
    state: "{{ item.value.state }}"
    inputs: "{{ item.value.inputs }}"
    validate_certs: false
  loop: "{{ lookup('dict', custom_credentials, wantlist=True) }}"
  when: custom_credentials is defined

- name: Add inventory
  awx.awx.inventory:
    name: "{{ item.value.name }}"
    description: "{{ item.value.description | default (omit) }}"
    organization: "{{ item.value.organization }}"
    state: "{{ item.value.state }}"
    validate_certs: false
  loop: "{{ lookup('dict', inventories, wantlist=True) }}"
  when: inventories is defined

- name: Add an inventory source
  awx.awx.inventory_source:
    name: "{{ item.value.name }}"
    description: "{{ item.value.description }}"
    inventory: "{{ item.value.inventory }}"
    credential: "{{ item.value.credential }}"
    overwrite: true
    update_on_launch: true
    source: "{{ item.value.source }}"
    organization: "{{ item.value.organization }}"
    source_vars: "{{ item.value.source_vars }}"
  loop: "{{ lookup('dict', inventorySource, wantlist=True) }}"
  when: inventorySource is defined

- name: Update a single inventory source
  awx.awx.inventory_source_update:
    name: "{{ item.value.name }}"
    inventory: "{{ item.value.inventory }}"
    organization: "{{ item.value.organization }}"
  loop: "{{ lookup('dict', inventorySource, wantlist=True) }}"
  when: inventorySource is defined

- name: Add host
  awx.awx.host:
    name: "{{ item.value.name }}"
    description: "{{ item.value.description | default (omit) }}"
    inventory: "{{ item.value.inventory }}"
    state: "{{ item.value.state }}"
    variables: "{{ item.value.vmVariables | default (omit) }}"
    validate_certs: false
  loop: "{{ lookup('dict', hosts, wantlist=True) }}"
  when: hosts is defined

- name: Create projects
  awx.awx.project:
    name: "{{ item.value.name }}"
    description: "{{ item.value.description }}"
    organization: "{{ item.value.organization }}"
    scm_url: "{{ item.value.scm_url }}"
    scm_type: "{{ item.value.scm_type }}"
    credential: "{{ item.value.credential }}"
    state: "{{ item.value.state }}"
    scm_update_on_launch: "{{ item.value.scm_update_on_launch | default(omit) }}"
    scm_update_cache_timeout: "{{ item.value.scm_update_cache_timeout | default(omit) }}"
    validate_certs: false
  loop: "{{ lookup('dict', projects, wantlist=True) }}"
  when: projects is defined

- name: Add EE to the controller instance
  awx.awx.execution_environment:
    name: "{{ item.value.name }}"
    image: "{{ item.value.image }}"
    pull: "{{ item.value.pull }}"
    credential: "{{ item.value.credential }}"
    validate_certs: false
  loop: "{{ lookup('dict', execution_environment, wantlist=True) }}"
  when: execution_environment is defined

- name: Create job templates
  awx.awx.job_template:
    name: "{{ item.value.name }}"
    job_type: "run"
    organization: "{{ item.value.organization }}"
    inventory: "{{ item.value.inventory }}"
    project: "{{ item.value.project }}"
    playbook: "{{ item.value.playbook }}"
    credentials: "{{ item.value.credentials }}"
    execution_environment: "{{ item.value.executionenv }}"
    state: "{{ item.value.state }}"
    ask_verbosity_on_launch: "{{ item.value.ask_verbosity_on_launch }}"
    validate_certs: true
    survey_enabled: "{{ item.value.survey_enabled | default(omit) }}"
    survey_spec: "{{ item.value.survey_spec | default(omit) }}"
    extra_vars: "{{ item.value.extraVars | default(omit) }}"
  loop: "{{ lookup('dict', job_templates, wantlist=True) }}"
  when: job_templates is defined

- name: Build a schedule for every day except saturday and sunday using the rruleset plugin
  awx.awx.schedule:
    name: "{{ item.value.name }}"
    state: "{{ item.value.state }}"
    job_type: "{{ item.value.job_type }}"
    extra_data: "{{ item.value.extra_data }}"
    unified_job_template: "{{ item.value.unified_job_template }}"
    rrule: "{{ query('awx.awx.schedule_rruleset',  '{{ start_date }} {{ cron_time }}', rules=rrules, timezone='Europe/Berlin') }}"
  loop: "{{ lookup('dict', scheduler, wantlist=True) }}"
  when: scheduler is defined and target_host != 'localhost'

- name: Create workflow job template
  awx.awx.workflow_job_template:
    name: "{{ item.value.name }}"
    inventory: "{{ item.value.inventory }}"
    state: "{{ item.value.state }}"
    survey_enabled: "{{ item.value.survey_enabled | default(omit) }}"
    survey_spec: "{{ item.value.survey_spec | default(omit) }}"
    extra_vars: "{{ item.value.extra_vars | default(omit) }}"
    workflow_nodes:
      - identifier: render-upload-template
        unified_job_template:
          organization:
            name: stuttgart-things
          name: render-upload-template
          type: job_template
        credentials: "{{ item.value.credentials }}"
        extra_data: "{{ item.value.extra_data_render }}"
        related:
          success_nodes:
            - identifier: get-execute-terraform
          failure_nodes: []
          always_nodes: []
      - identifier: get-execute-terraform
        unified_job_template:
          organization:
            name: stuttgart-things
          name: get-execute-terraform
          type: job_template
        credentials: "{{ item.value.credentials }}"
        extra_data: "{{ item.value.extra_data_execute }}"
        related:
          success_nodes:
            - identifier: inventory-sync
          failure_nodes: []
          always_nodes: []
      - identifier: inventory-sync
        unified_job_template:
          name: source-dynamic-inventory
          inventory:
            organization:
              name: "{{ item.value.organization }}"
          type: inventory_source
  loop: "{{ lookup('dict', workflow_job_templates, wantlist=True) }}"
  when: workflow_job_templates is defined
```

-----------------------------------------------------------------
check_connection.yaml
```
---
- name: Pause play until awx is reachable from the Ansible Controller
  ansible.builtin.uri:
    url: "{{ controller_host }}api/v2"
    method: GET
  register: _result
  until: _result.status == 200
  retries: 10
  delay: 120
  tags: [ 'init' ]
```

--------------------------------------------------------------------
survey-workflow.yaml
```
{
    "name": "",
    "description": "",
    "spec": [
      {
        "question_name": "What is the VM name?",
        "question_description": "Enter VM name",
        "required": false,
        "type": "text",
        "variable": "vmName",
        "min": null,
        "max": null,
        "default": ""
      },
      {
        "question_name": "What is the VM size?",
        "question_description": "Enter VM sizes s,m,l or xl",
        "required": false,
        "type": "multiplechoice",
        "variable": "vmSize",
        "choices": ["s", "m", "l", "xl"],
        "min": null,
        "max": null,
        "default": "s"
      },
      {
        "question_name": "How many VMs?",
        "question_description": "Enter VM count",
        "required": false,
        "type": "multiplechoice",
        "variable": "vmCount",
        "choices": ["1", "2", "3", "4", "5"],
        "min": null,
        "max": null,
        "default": "1"
      },
      {
        "question_name": "Which VM template do you want to use? (see description)",
        "question_description": "Choose os",
        "required": false,
        "type": "multiplechoice",
        "variable": "vmTemplate",
        "choices": ["ubuntu22", "ubuntu24", "rocky9"],
        "min": null,
        "max": null,
        "default": ""
      },
      {
        "question_name": "What is the bucket name in s3?",
        "question_description": "Enter bucket name to PUT templates",
        "required": false,
        "type": "text",
        "variable": "bucket_name",
        "min": null,
        "max": null,
        "default": ""
      },
      {
        "question_name": "What is the platform subfolderpath?",
        "question_description": "Enter subfolderpath of vsphere (testing)/ proxmox (stuttgart-things)",
        "required": false,
        "type": "text",
        "variable": "subfolderpath",
        "min": null,
        "max": null,
        "default": "testing"
      },
      {
        "question_name": "What lab?",
        "question_description": "Choose labul or labda",
        "required": false,
        "type": "multiplechoice",
        "variable": "lab",
        "choices": ["labul", "labda"],
        "min": null,
        "max": null,
        "default": "labul"
      },
      {
        "question_name": "What cloud for the VM?",
        "question_description": "Choose cloud",
        "required": false,
        "type": "multiplechoice",
        "variable": "cloud",
        "choices": ["vsphere", "proxmox"],
        "min": null,
        "max": null,
        "default": "vsphere"
      },
      {
        "question_name": "Do you want to install Terraform?",
        "question_description": "Choose true or false",
        "required": false,
        "type": "text",
        "variable": "install_terraform",
        "min": null,
        "max": null,
        "default": "true"
      },
      {
        "question_name": "What is the project name?",
        "question_description": "Enter project name (name of vm)",
        "required": false,
        "type": "text",
        "variable": "project_name",
        "min": null,
        "max": null,
        "default": ""
      },
      {
        "question_name": "What is the object name in s3?",
        "question_description": "Enter object name to GET config",
        "required": false,
        "type": "text",
        "variable": "object_name",
        "min": null,
        "max": null,
        "default": ""
      },
      {
        "question_name": "What is the s3 endpoint?",
        "question_description": "Enter s3 endpoint",
        "required": false,
        "type": "text",
        "variable": "s3_endpoint",
        "min": null,
        "max": null,
        "default": "https://artifacts.andre-dev.sthings-vsphere.labul.sva.de"
      },
      {
        "question_name": "Do you want to apply or destroy VM?",
        "question_description": "Enter state of terrform VM",
        "required": false,
        "type": "multiplechoice",
        "variable": "state",
        "choices": ["present", "absent"],
        "min": null,
        "max": null,
        "default": "present"
      }
    ]
  }

```

-----------------------------------------------------------------
job-workflow.yaml
```
---
workflow_job_templates:
  stuttgartThings:
    name: testing-workflow
    organization: stuttgart-things
    inventory: dynamic-inventory-vsphere
    credentials:
      - sthings-ssh
      - labul-vault
    executionenv: sthings-ee
    state: present
    survey_enabled: true
    survey_spec: "{{ lookup('file', 'vars/survey-workflow.yaml') }}"
    #extra_vars: {'target_host': 'andre-dev-u22', 'vmName': 'awx-test-{{ lookup("community.general.random_string", length=5, special=false) | lower }}', 'vmSize': 's', 'vmCount': '1', 'vmTemplate': 'ubuntu24', 'bucket_name': 'andre-vm-config', 'subfolderpath': 'testing', 'lab': 'labul', 'cloud': 'vsphere', 'install_terraform': 'true', 'project_name': 'awx-test', 'object_name': '{{ ansible_date_time.date }}-awx-test.tf', 's3_endpoint': 'https://artifacts.andre-dev.sthings-vsphere.labul.sva.de', 'state': 'present'}
    extra_data_render: "{'target_host': 'localhost'}"
    extra_data_execute: "{'target_host': 'andre-dev-u22'}"
```
