### ISSUE TITLE
[ANSIBLE][TESTING] - PLAY TESTING IN JOB/TEKTON

### ISSUE THREAD

**Issue by patrick-hermann-sva** [stuttgart-things/stuttgart-things#640]
WORKING JOB EXAMPLE

```yaml
---
# Source: sthings-cluster/templates/config-map.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ansible
  namespace: default
data:
  namespace: default
  test.yaml: |
    ---
    - hosts: localhost
      gather_facts: true
      become: true
  
      tasks:
        - shell: |
            whoami
            hostname
            curl -LO https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl
            chmod +x kubectl
            cp -R kubectl /usr/local/bin/
            kubectl version --client
---
# Source: sthings-cluster/templates/job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: baseos-setup
  namespace: default
  labels:
    app: machine-shop-operator
    machine-shop-operator: ansible
spec:
  backoffLimit: 5
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: baseos-setup
      labels:
        app: machine-shop-operator
        machine-shop-operator: ansible
    spec:
      containers:
        - name: manager
          image: eu.gcr.io/stuttgart-things/sthings-ansible:10.1.0-1
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            runAsNonRoot: false
            readOnlyRootFilesystem: false
          env:
            - name: ANSIBLE_HOST_KEY_CHECKING
              value: "False"
            - name: INV_PATH
              value: "/tmp/inv"
            - name: TARGETS
              value: "localhost"
          envFrom:
            - configMapRef:
                name: ansible
          resources:
            requests:
              cpu: 10m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 768Mi
          command:
            - /bin/sh
            - -ec
            - ansible-galaxy collection install https://github.com/stuttgart-things/stuttgart-things/releases/download/0.5.33/sthings-base_os-0.5.33.tar.gz && ansible-playbook sthings.base_os.binaries -e target_host=localhost -vv
          volumeMounts:
            - name: ansible
              mountPath: /tmp/test
      restartPolicy: Never
      volumes:
        - name: ansible
          configMap:
            name: ansible
```

## CHART

```yaml
---
configmaps:

  ansible:
    namespace: default
    test.yaml: |
      ---
      - hosts: localhost
        gather_facts: true
        become: true

        tasks:
          - shell: |
              whoami
              hostname
              curl -LO https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl
              chmod +x kubectl
              cp -R kubectl /usr/local/bin/
              kubectl version --client

jobs:
  baseos-setup:
    name: baseos-setup
    namespace: default
    labels:
      app: machine-shop-operator
      machine-shop-operator: ansible
    restartPolicy: Never
    volumes:
      ansible:
        volumeKind: configMap
    containers:
      manager:
        image: eu.gcr.io/stuttgart-things/sthings-ansible
        tag: 10.1.0-1
        imagePullPolicy: Always
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          TARGETS: "localhost"
          INV_PATH: "/tmp/inv"
        securityContext:
          runAsUser: 0 #65532
          allowPrivilegeEscalation: true
          privileged: true
          runAsNonRoot: false
          readOnlyRootFilesystem: false
        command:
          - "/bin/sh"
          - "-ec"
          - "ansible-galaxy collection install https://github.com/stuttgart-things/stuttgart-things/releases/download/0.5.33/sthings-base_os-0.5.33.tar.gz && ansible-playbook sthings.base_os.binaries -e target_host=localhost -vv"
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 768Mi
        volumeMounts:
          ansible:
            mountPath: /tmp/test
# helm template sthings-cluster --values ../job.yaml > /tmp/test.yaml
```

![image](https://github.com/user-attachments/assets/d58977e3-5787-44dc-a23a-8fd24530c96f)
