### ISSUE TITLE
[HELM][HELMFILE] - ADD HELMFILE FOR REGISTRY

### ISSUE THREAD

**Issue by patrick-hermann-sva** [stuttgart-things/stuttgart-things#643]
create helmfile out of this information - create env andre-dev. structure like the other helmfiles.

deployment 

```bash
# helm repo add twuni https://helm.twun.io
# helm repo update
# helm upgrade --install registry twuni/docker-registry --version 2.2.3 --values registry/values.yaml -n registry --create-namespace
```

values

```yaml
---
persistence:
  accessMode: 'ReadWriteOnce'
  enabled: false
  size: 10Gi
  storageClass: nfs-csi

ingress:
  enabled: true
  className: nginx
  path: /
  hosts:
    - registry.app-dev.sthings-vsphere.labul.sva.de
  annotations:
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
  tls:
    - secretName: registry-kibana-tls
      hosts:
        - registry.app-dev.sthings-vsphere.labul.sva.de

secrets:
  haSharedSecret: ""
  htpasswd: |-
    sthings:$2y$05$CrDbu7Cb7R9ZwF4HGmlFcOWIpW/W4OruCU.qbZYN2T/ZhTC0YW/ei
```

cert

```yaml
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-ingress
  namespace: registry
spec:
  commonName: registry.app-dev.sthings-vsphere.labul.sva.de
  dnsNames:
    - registry.app-dev.sthings-vsphere.labul.sva.de
  issuerRef:
    kind: ClusterIssuer
    name: vault-approle
  secretName: registry-tls
```
