### ISSUE TITLE
[AWX][COLLECTION] - CREATE JSON SURVEY JSON FILES AS TEMPLATE

### ISSUE THREAD

**Issue by patrick-hermann-sva** [stuttgart-things/stuttgart-things#693]
```yaml
---
- hosts: localhost
  vars:
    questions:
      target_host:
        name: Execute against which host?
        description: Enter host name
        required: true
        type: text
        variable: target_host
        min: "null"
        max: "null"
        default: ""
      nerdctl_version:
        name: nerdctl version?
        description: choose nerdctl version
        required: true
        type: multiplechoice
        variable: nerdctl_version
        min: "null"
        max: "null"
        choices: '["1.7.5", "1.7.6", "2.0.0-beta.5"]'
        default: 1.7.6

  tasks:
    - name: Render template
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - { src: "survey.json.j2", dest: "rendred.json" }
```

```json
#survey.json.j2
{
    "name": "",
    "description": "",
    "spec": [
    {% for question in questions.values() %}
    {
        "question_name": "{{ question.name }}",
        "question_description": "{{ question.description }}",
        "required": {{ question.required | lower }},
        "type": "{{ question.type }}",
        "variable": "{{ question.variable }}",
        "min": {{ question.min }},
        "max": {{ question.max }},
        {% if question.choices is defined %}
        "choices": {{ question.choices }},
        {% endif %}
        "default": "{{ question.default }}"
    }{% if not loop.last %},{% endif %}{% endfor %}
    ]
}
```
