### ISSUE TITLE
[AWX][DEPLOYMENT] - ADD INSTANCES AS DICT

### ISSUE THREAD

**Issue by patrick-hermann-sva** [stuttgart-things/stuttgart-things#695]
please take this wip/example code and add for instances AND for certifcates!

```yaml
---
customresources:
{{- range $k, $v := .Values.instances }}
  {{ $k }}:
    apiVersion: awx.ansible.com/v1beta1
    kind: AWX
    metadata:
      name: {{ $v.name }}
      namespace: {{ $v.namespace }}
    spec:
      admin_user: {{ $v.adminUser  }}
{{- end }}
```

```yaml
# env file should not be defaults like in the scrreshot 
instances:
  dev:
    name: awx-dev
    namespace: awx
    adminUser: admin
  prod:
    name: awx-dev
    namespace: awx
    adminUser: sthings
```

![image](https://github.com/user-attachments/assets/dd2d0ede-abc5-43c8-b98b-7ce1bef4a829)
